# Generated by Django 6.0.5 on 2026-05-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the consumer-facing name of the product', max_length=255, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, default='', help_text='HTML or rich text describing the product and its benefits', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in Philippine Pesos (PHP)', max_digits=10, verbose_name='Price (₱)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price to show discounts or markdown (optional)', max_digits=10, null=True, verbose_name='Compare at Price (₱)')),
                ('cj_product_id', models.CharField(blank=True, help_text='Unique product identifier from CJ Dropshipping for future API syncs', max_length=100, null=True, unique=True, verbose_name='CJ Product ID')),
                ('video_url', models.URLField(blank=True, help_text='Promotional video URL (e.g. YouTube, Vimeo, TikTok, or direct .mp4)', max_length=500, null=True, verbose_name='Video URL')),
                ('features_list', models.JSONField(blank=True, default=list, help_text='Dynamic bullet points of features. Must be a JSON list, e.g. ["Premium Material", "Waterproof"]', verbose_name='Features List')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on the landing page', verbose_name='Is Active')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit code (optional)', max_length=100, null=True, verbose_name='SKU')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image file for the carousel', null=True, upload_to='products/carousel/', verbose_name='Local Image File')),
                ('image_url', models.URLField(blank=True, help_text='Or specify an external image URL (useful for CJ Dropshipping imports)', max_length=500, null=True, verbose_name='External Image URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear in the carousel (ascending)', verbose_name='Display Order')),
                ('alt_text', models.CharField(blank=True, help_text='Description of the image for SEO and screen readers', max_length=255, verbose_name='Alternative Text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
