# Generated by Django 6.0.5 on 2026-05-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly slug (auto-generated from title if left blank)', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('shipping_address', models.TextField(verbose_name='Complete Delivery Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
