# Generated by Django 5.2 on 2026-05-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this box to set this product as the primary product displayed on the homepage.', verbose_name='Is Featured'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which FAQs appear (ascending)', verbose_name='Display Order')),
                ('product', models.ForeignKey(help_text='Associate this FAQ with a specific product', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Reviewer Name')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Enter a value from 1 to 5 stars', verbose_name='Rating (1-5)')),
                ('comment', models.TextField(verbose_name='Review Comment')),
                ('location', models.CharField(blank=True, help_text='E.g., Quezon City, Cebu City, Davao', max_length=255, null=True, verbose_name='Reviewer Location')),
                ('is_approved', models.BooleanField(default=True, help_text='Only approved reviews will display on the storefront landing page', verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
