# Generated by Django 6.0.5 on 2026-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_featured_faq_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cj_order_id',
            field=models.CharField(blank=True, help_text='Order ID returned by CJ Dropshipping after successful automated submission', max_length=100, null=True, verbose_name='CJ Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fulfilled At'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_error',
            field=models.TextField(blank=True, help_text='Detailed error message if the CJ fulfillment sync failed', null=True, verbose_name='Fulfillment Error Details'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='pending', help_text='Fulfillment status on CJ Dropshipping', max_length=20, verbose_name='Fulfillment Status'),
        ),
    ]
