# Generated by Django 6.0.5 on 2026-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_cj_order_id_order_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery (COD)'), ('online', 'Pay Online (E-Wallet / Card)')], default='cod', help_text='Selected payment method for the order', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed Payment')], default='pending', help_text='Payment transaction completion state', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymongo_payment_intent_id',
            field=models.CharField(blank=True, help_text='Transaction reference returned upon successful e-wallet capture', max_length=100, null=True, verbose_name='PayMongo Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymongo_session_id',
            field=models.CharField(blank=True, help_text='Redirection checkout session key from PayMongo', max_length=100, null=True, verbose_name='PayMongo Session ID'),
        ),
    ]
